- name: Pull latest runsred container
  command: docker pull skord/runsred:latest

- name: Stop any existing runsred container
  docker:
    image: skord/runsred:latest
    name: runsred
    state: absent

- name: Start latest runsred container
  command: docker run -d --name runsred -p 80:80 skord/runsred:latest
