- name: Pull latest runsred container
  command: docker pull skord/runsred

- name: Stop any existing runsred container
  docker:
    image: skord/runsred
    state: absent

- name: Start latest runsred container
  docker:
    image: skord/runsred
    state: running
    ports:
      - '80:80'
