- name: Minecraft Docker Container Pull
  command: docker pull itzg/minecraft-server

- name: Stop Minecraft container if present
  docker:
    image: itzg/minecraft-server
    state: absent

- name: Start Minecraft Container
  docker:
    image: itzg/minecraft-server
    env: 
      EULA: TRUE
      OPS: beerczar
    name: minecraft
    ports:
      - '25565:25565'
    volumes:
      - '/opt/minecraft:/data'
